# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import disc_pb2 as disc__pb2


class RegisterReplicaServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.mapper = channel.unary_unary(
                '/disc.RegisterReplicaService/mapper',
                request_serializer=disc__pb2.str.SerializeToString,
                response_deserializer=disc__pb2.StringInt32Dictionary.FromString,
                )
        self.reducer = channel.unary_unary(
                '/disc.RegisterReplicaService/reducer',
                request_serializer=disc__pb2.red.SerializeToString,
                response_deserializer=disc__pb2.void.FromString,
                )


class RegisterReplicaServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def mapper(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def reducer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RegisterReplicaServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'mapper': grpc.unary_unary_rpc_method_handler(
                    servicer.mapper,
                    request_deserializer=disc__pb2.str.FromString,
                    response_serializer=disc__pb2.StringInt32Dictionary.SerializeToString,
            ),
            'reducer': grpc.unary_unary_rpc_method_handler(
                    servicer.reducer,
                    request_deserializer=disc__pb2.red.FromString,
                    response_serializer=disc__pb2.void.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'disc.RegisterReplicaService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RegisterReplicaService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def mapper(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/disc.RegisterReplicaService/mapper',
            disc__pb2.str.SerializeToString,
            disc__pb2.StringInt32Dictionary.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def reducer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/disc.RegisterReplicaService/reducer',
            disc__pb2.red.SerializeToString,
            disc__pb2.void.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
